name = "anonymous-speech-platform-admin"
main = "worker/src/index.js"
compatibility_date = "2026-10-01"

[vars]
ADMIN_API_ENABLED = "true"

[[d1_databases]]
binding = "DB"
database_name = "anonymous-speech-research-staging"
database_id = "629bd064-2df8-413c-bcc0-6f46dfe3bdd3"

[[r2_buckets]]
binding = "AUDIO"
bucket_name = "anonymous-speech-audio-staging"

[assets]
directory = "./public"
run_worker_first = ["/admin/api/*"]
